### PR TITLE
Adds support for rails 4

### PR DESCRIPTION
**Pull request by arturopie**

### CODE REVIEW

**Comment by marcandre** [comment]
Awesome, thanks!

If it's easy for you, could you make the pull request based on https://github.com/timcharper/calendar_date_select?

I'd rather merge it there. I probably should delete my fork, actually.

**Comment by arturopie** [comment]
I found this gem (https://rubygems.org/gems/calendar_date_select) is pointing to this repo. Is that true? What gem should I use?

**Comment by marcandre** [comment]
Mmm, you're right. Let me see...

**Comment by marcandre** [comment]
Ok, released 2.1.0 with your fix. Thanks! :smile:

**Pull request merged**
